// Subject theme config — used across dashboard, modules, and agent
export const SUBJECT_THEMES = {
  'Economics': {
    emoji: '📈',
    color: '#166534',
    light: '#dcfce7',
    accent: '#16a34a',
    bg: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    tagline: 'Markets, models & mechanisms',
    decoration: '↗ ↘ ↗ ↗',
  },
  'Biology': {
    emoji: '🧬',
    color: '#0f766e',
    light: '#ccfbf1',
    accent: '#14b8a6',
    bg: 'linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%)',
    tagline: 'Life at every scale',
    decoration: '◉ ○ ◉ ●',
  },
  'Chemistry': {
    emoji: '⚗️',
    color: '#6d28d9',
    light: '#ede9fe',
    accent: '#7c3aed',
    bg: 'linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)',
    tagline: 'Structure, reaction & discovery',
    decoration: '⬡ ⬢ ⬡ ⬡',
  },
  'Physics': {
    emoji: '⚛️',
    color: '#1d4ed8',
    light: '#dbeafe',
    accent: '#2563eb',
    bg: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)',
    tagline: 'Forces, fields & fundamentals',
    decoration: '~ ~ ~ ~',
  },
  'Mathematics': {
    emoji: '📐',
    color: '#3730a3',
    light: '#e0e7ff',
    accent: '#4f46e5',
    bg: 'linear-gradient(135deg, #eef2ff 0%, #e0e7ff 100%)',
    tagline: 'Proof, patterns & precision',
    decoration: '∫ ∑ π ∞',
  },
  'History': {
    emoji: '📜',
    color: '#92400e',
    light: '#fef3c7',
    accent: '#d97706',
    bg: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)',
    tagline: 'Cause, consequence & continuity',
    decoration: '— — — —',
  },
  'Psychology': {
    emoji: '🧠',
    color: '#0e7490',
    light: '#cffafe',
    accent: '#0891b2',
    bg: 'linear-gradient(135deg, #ecfeff 0%, #cffafe 100%)',
    tagline: 'Behaviour, cognition & culture',
    decoration: '◡ ◡ ◡ ◡',
  },
  'Computer Science': {
    emoji: '💻',
    color: '#0f172a',
    light: '#e2e8f0',
    accent: '#334155',
    bg: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)',
    tagline: 'Algorithms, systems & solutions',
    decoration: '{ } [ ] ;',
  },
  'Geography': {
    emoji: '🌍',
    color: '#15803d',
    light: '#bbf7d0',
    accent: '#16a34a',
    bg: 'linear-gradient(135deg, #f0fdf4 0%, #bbf7d0 100%)',
    tagline: 'Place, space & global change',
    decoration: '— ≈ — ≈',
  },
  'Philosophy': {
    emoji: '💭',
    color: '#475569',
    light: '#e2e8f0',
    accent: '#64748b',
    bg: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)',
    tagline: 'Questions that outlast answers',
    decoration: '? → ? ∴',
  },
  'Visual Arts': {
    emoji: '🎨',
    color: '#c2410c',
    light: '#fed7aa',
    accent: '#ea580c',
    bg: 'linear-gradient(135deg, #fff7ed 0%, #fed7aa 100%)',
    tagline: 'Meaning through making',
    decoration: '● ○ ■ □',
  },
  'Music': {
    emoji: '🎵',
    color: '#9d174d',
    light: '#fce7f3',
    accent: '#be185d',
    bg: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)',
    tagline: 'Sound, structure & expression',
    decoration: '♩ ♪ ♫ ♬',
  },
  'English A': {
    emoji: '📚',
    color: '#92400e',
    light: '#fef3c7',
    accent: '#b45309',
    bg: 'linear-gradient(135deg, #fffbeb 0%, #fef9c3 100%)',
    tagline: 'Language, literature & meaning',
    decoration: '" " — "',
  },
  'Business Management': {
    emoji: '💼',
    color: '#075985',
    light: '#bae6fd',
    accent: '#0369a1',
    bg: 'linear-gradient(135deg, #f0f9ff 0%, #bae6fd 100%)',
    tagline: 'Strategy, systems & growth',
    decoration: '↑ → ↑ ↑',
  },
  'Environmental Systems & Societies': {
    emoji: '🌿',
    color: '#14532d',
    light: '#bbf7d0',
    accent: '#15803d',
    bg: 'linear-gradient(135deg, #f0fdf4 0%, #d1fae5 100%)',
    tagline: 'Planet, policy & people',
    decoration: '∿ ∿ ∿ ∿',
  },
  'Global Politics': {
    emoji: '🌐',
    color: '#1e3a8a',
    light: '#bfdbfe',
    accent: '#1d4ed8',
    bg: 'linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)',
    tagline: 'Power, governance & change',
    decoration: '○ ◉ ○ ○',
  },
  'Language B': {
    emoji: '🗣️',
    color: '#5b21b6',
    light: '#ede9fe',
    accent: '#7c3aed',
    bg: 'linear-gradient(135deg, #faf5ff 0%, #ede9fe 100%)',
    tagline: 'Communication across cultures',
    decoration: 'A B C …',
  },
  'Social & Cultural Anthropology': {
    emoji: '🏛️',
    color: '#78350f',
    light: '#fef3c7',
    accent: '#92400e',
    bg: 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)',
    tagline: 'Society, culture & identity',
    decoration: '◆ ◇ ◆ ◇',
  },
  'Other': {
    emoji: '✦',
    color: '#0a0a0a',
    light: '#f5f5f5',
    accent: '#555',
    bg: 'linear-gradient(135deg, #fafafa 0%, #f5f5f5 100%)',
    tagline: 'Your unique EE journey',
    decoration: '· · · ·',
  },
}

export function getTheme(subject) {
  return SUBJECT_THEMES[subject] || SUBJECT_THEMES['Other']
}
