'use client'

import GuidePage from '../../components/GuidePage'

const CONTENT = [
  { type: 'paragraph', text: 'Before you submit your Extended Essay, run through this checklist. These are the things examiners immediately notice — and most of them take under 15 minutes to fix. This checklist is built from the same system used to score 32/34.' },
  { type: 'heading', text: 'Research Question' },
  { type: 'key-takeaway', items: [
    'RQ uses "to what extent" or "how" — forces evaluation, not just description',
    'RQ is answerable within 4,000 words (not a PhD thesis)',
    'RQ is researchable — you have actual sources that address it',
    'RQ appears on the title page and is consistent throughout the essay',
    'RQ has been approved by your EE supervisor',
  ]},
  { type: 'heading', text: 'Title Page' },
  { type: 'key-takeaway', items: [
    'Includes: essay title, research question, subject, word count, and session (e.g., May 2026)',
    'Does NOT include: your name, school name, or candidate number',
    'No decorative elements, borders, colours, or images',
    'Centred and clean — looks like an academic journal cover page',
  ]},
  { type: 'heading', text: 'Structure and Organisation' },
  { type: 'key-takeaway', items: [
    'Table of contents with correct page numbers (use auto-generated TOC)',
    'All required sections present: Introduction, body sections, Conclusion',
    'Headings are consistent in style (all H1s match, all H2s match)',
    'Logical flow: each section builds on the previous one',
    'Introduction ends by setting up the approach, conclusion directly answers the RQ',
  ]},
  { type: 'heading', text: 'Content and Analysis' },
  { type: 'key-takeaway', items: [
    'Every section primarily answers the research question — no purposeless content',
    'Analysis-to-description ratio: significantly more analysis than description',
    'Every analytical claim is supported by cited evidence',
    'All frameworks introduced in methodology are applied in the analysis',
    'Counterarguments or limitations are acknowledged and addressed',
    'Conclusion synthesises findings and directly answers the RQ',
  ]},
  { type: 'heading', text: 'Formatting' },
  { type: 'key-takeaway', items: [
    'Font: Times New Roman, 12pt throughout',
    'Spacing: double-spaced throughout (except block quotes and bibliography)',
    'Margins: 1 inch (2.54cm) on all sides',
    'Page numbers: top right, starting from first content page',
    'Alignment: left-aligned (not justified)',
    'Paragraph indentation: first line 1.27cm using Tab, not spacebar',
  ]},
  { type: 'heading', text: 'Citations and Bibliography' },
  { type: 'key-takeaway', items: [
    'One citation style used consistently: either MLA or footnotes — never both',
    'In-text citations placed after closing quotation mark, before period',
    'Every in-text citation has a matching entry in the bibliography',
    'Bibliography is alphabetical by author\'s last name',
    'Hanging indent format (first line flush left, subsequent lines indented)',
    'Double-spaced throughout bibliography',
    'No sources listed that weren\'t actually cited in the essay',
  ]},
  { type: 'heading', text: 'Word Count' },
  { type: 'key-takeaway', items: [
    'Word count is between 3,500 and 4,000 words',
    'Word count includes: introduction, body sections, conclusion',
    'Word count EXCLUDES: title page, table of contents, bibliography, appendices, footnotes',
    'Word count is stated accurately on the title page',
  ]},
  { type: 'heading', text: 'Figures, Tables, and Visuals' },
  { type: 'key-takeaway', items: [
    'Every figure is labelled (Fig 1, Fig 2...) with a brief description',
    'Every table is labelled (Table 1, Table 2...) with a brief description',
    'Each visual is referenced in the text before or after it appears',
    'All visuals have a source cited (including self-created ones: "Author\'s own calculations")',
    'No visuals included that aren\'t directly referenced in the analysis',
  ]},
  { type: 'heading', text: 'Academic Integrity' },
  { type: 'key-takeaway', items: [
    'All sources cited — every fact, statistic, and argument that isn\'t your original idea',
    'No text generated by AI in any part of the essay',
    'No content copied from essay banks (Clastify, Prezi, other students)',
    'All paraphrasing properly cited — not just word-swapped from the original',
    'Turnitin similarity under 15-20% (ask supervisor to check before final submission)',
  ]},
  { type: 'heading', text: 'Final Read-Through' },
  { type: 'warning-box', text: 'Do this once, before you submit. Read your entire essay aloud or have someone else read it. You will catch: "it\'s" vs "its" errors, typos and autocorrect mistakes, sentences that don\'t make sense, inconsistencies between sections. This takes 15-20 minutes. It is the easiest mark protection available to you.' },
  { type: 'tip-box', text: 'Specifically check for: consistent use of the same company/person/concept names throughout, consistent capitalisation of proper nouns, consistency between what you promise in your methodology and what you actually deliver in your analysis.' },
  { type: 'cta-box', label: 'Free tool', text: 'Track your sources as you research and generate your MLA bibliography automatically with the EE Dump.', href: '/dashboard/dump', buttonText: 'Try EE Dump free' },
  { type: 'key-takeaway', items: [
    'Formatting check: 5 minutes — font, spacing, margins, page numbers',
    'Citations check: 10 minutes — one style used, every citation has a bibliography entry',
    'Word count check: 2 minutes — between 3,500 and 4,000, stated on title page',
    'Read-through: 15-20 minutes — catch typos and inconsistencies',
    'Total pre-submission check: under 30 minutes. Do not skip it.',
  ]},
]

const RELATED = [
  { href: '/guides/ee-formatting-guide', title: 'Full EE Formatting Guide', description: 'Font, spacing, headings — all the formatting rules in detail.' },
  { href: '/guides/ee-citations-mla', title: 'EE Citations and MLA Guide', description: 'How to format citations and your Works Cited page.' },
]

const FAQ = [
  { question: 'What\'s the penalty for exceeding 4,000 words?', answer: 'Examiners stop reading at 4,000 words. If your conclusion or key arguments fall after word 4,000, they won\'t be assessed. Cut the essay down before submission — it\'s better to have a tighter 3,800-word essay than a sprawling 4,200-word one where your conclusion is ignored.' },
  { question: 'Can I submit my EE without my supervisor reading the final draft?', answer: 'Technically yes, but this is strongly inadvisable. Your supervisor\'s feedback on the final draft often catches structural or RQ issues that can be fixed before submission. Use every opportunity your school provides for supervisor feedback.' },
  { question: 'What if I notice a mistake after submitting?', answer: 'Once submitted, you generally cannot make changes. This is why the pre-submission checklist matters. Check everything before you click submit.' },
]

export default function EEChecklist() {
  return (
    <GuidePage
      title="IB Extended Essay Submission Checklist"
      description="Before you submit your EE, run through this checklist. These are the things examiners immediately notice — RQ framing, formatting, citations, word count, and the 15-minute read-through that protects your grade."
      canonical="/guides/ee-checklist"
      content={CONTENT}
      relatedGuides={RELATED}
      faqItems={FAQ}
    />
  )
}
